In [1]:
import pandas as pd

data = pd.read_csv("/content/academic Stress level - maintainance 1.csv")
data

,Timestamp,Your Academic Stage,Peer pressure,Academic pressure from your home,Study Environment,What coping strategy you use as a student?,"Do you have any bad habits like smoking, drinking on a daily basis?",What would you rate the academic competition in your student life,Rate your academic stress index
0,24/07/2025 22:05:39,undergraduate,4,5,Noisy,Analyze the situation and handle it with intel...,No,3,5
1,24/07/2025 22:05:52,undergraduate,3,4,Peaceful,Analyze the situation and handle it with intel...,No,3,3
2,24/07/2025 22:06:39,undergraduate,1,1,Peaceful,"Social support (friends, family)",No,2,4
3,24/07/2025 22:06:45,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,4,3
4,24/07/2025 22:08:06,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,4,5
...,...,...,...,...,...,...,...,...,...
135,17/08/2025 13:02:04,undergraduate,3,2,Peaceful,Analyze the situation and handle it with intel...,No,3,4
136,18/08/2025 14:36:00,undergraduate,4,2,disrupted,Analyze the situation and handle it with intel...,No,3,3
137,18/08/2025 17:13:52,undergraduate,3,3,Peaceful,Analyze the situation and handle it with intel...,No,2,4
138,18/08/2025 19:08:52,undergraduate,4,5,disrupted,"Social support (friends, family)",No,5,5
139,18/08/2025 22:40:13,undergraduate,4,2,Peaceful,"Social support (friends, family)",No,4,4

In [4]:
data.isna().sum()

Timestamp                                                              0
Your Academic Stage                                                    0
Peer pressure                                                          0
Academic pressure from your home                                       0
Study Environment                                                      1
What coping strategy you use as a student?                             0
Do you have any bad habits like smoking, drinking on a daily basis?    0
What would you rate the academic  competition in your student life     0
Rate your academic stress index                                        0
dtype: int64

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 9 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Timestamp                                                            140 non-null    object
 1   Your Academic Stage                                                  140 non-null    object
 2   Peer pressure                                                        140 non-null    int64
 3   Academic pressure from your home                                     140 non-null    int64
 4   Study Environment                                                    139 non-null    object
 5   What coping strategy you use as a student?                           140 non-null    object
 6   Do you have any bad habits like smoking, drinking on a daily basis?  140 non-null    object
 7   What would you rate the academic  competition in your student life   140 non-null    int64
 8   Rate your academic stress index                                      140 non-null    int64
dtypes: int64(4), object(5)
memory usage: 10.0+ KB

In [3]:
data['Your Academic Stage'].unique()

array(['undergraduate', 'high school', 'post-graduate'], dtype=object)

In [5]:
data.dropna(inplace = True)

In [6]:
data.isna().sum()

Timestamp                                                              0
Your Academic Stage                                                    0
Peer pressure                                                          0
Academic pressure from your home                                       0
Study Environment                                                      0
What coping strategy you use as a student?                             0
Do you have any bad habits like smoking, drinking on a daily basis?    0
What would you rate the academic  competition in your student life     0
Rate your academic stress index                                        0
dtype: int64

In [7]:
data['Your Academic Stage'].unique()

array(['undergraduate', 'high school', 'post-graduate'], dtype=object)

In [9]:
data["Peer pressure"].unique()

array([4, 3, 1, 5, 2])

In [10]:
data['Academic pressure from your home'].unique()

array([5, 4, 1, 2, 3])

In [11]:
data['Study Environment'].unique()

array(['Noisy', 'Peaceful', 'disrupted'], dtype=object)

In [12]:
data['What coping strategy you use as a student?'].unique()

array(['Analyze the situation and handle it with intellect',
       'Social support (friends, family)',
       'Emotional breakdown (crying a lot)'], dtype=object)

In [13]:
data['Do you have any bad habits like smoking, drinking on a daily basis?'].unique()

array(['No', 'prefer not to say', 'Yes'], dtype=object)

In [14]:
data['What would you rate the academic  competition in your student life'].unique()

array([3, 2, 4, 5, 1])

In [15]:
data['Rate your academic stress index '].unique()

array([5, 3, 4, 2, 1])

In [17]:
from sklearn.cluster import KMeans

X=data.drop(['Timestamp'],axis=1)

In [18]:
X.replace({
    'Your Academic Stage':{'undergraduate':0, 'high school':1, 'post-graduate':2},
    'Study Environment':{'Noisy':0, 'Peaceful':1, 'disrupted':2},
    'What coping strategy you use as a student?':{'Analyze the situation and handle it with intellect':0,
       'Social support (friends, family)':1,
       'Emotional breakdown (crying a lot)':2},
    'Do you have any bad habits like smoking, drinking on a daily basis?':{'No':0, 'prefer not to say':1, 'Yes':2}

},inplace = True)

/tmp/ipython-input-3418326518.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X.replace({

In [28]:
print(X.to_string())

     Your Academic Stage  Peer pressure  Academic pressure from your home  Study Environment  What coping strategy you use as a student?  Do you have any bad habits like smoking, drinking on a daily basis?  What would you rate the academic  competition in your student life  Rate your academic stress index
0                      0              4                                 5                  0                                           0                                                                    0                                                                   3                                 5
1                      0              3                                 4                  1                                           0                                                                    0                                                                   3                                 3
2                      0              1                                 1                  1                                           1                                                                    0                                                                   2                                 4
3                      0              3                                 2                  1                                           0                                                                    0                                                                   4                                 3
4                      0              3                                 3                  1                                           0                                                                    0                                                                   4                                 5
5                      0              3                                 3                  1                                           0                                                                    0                                                                   4                                 4
6                      0              5                                 5                  2                                           2                                                                    0                                                                   4                                 4
7                      0              3                                 2                  1                                           1                                                                    0                                                                   3                                 3
8                      0              2                                 2                  1                                           0                                                                    0                                                                   2                                 2
9                      0              2                                 2                  1                                           0                                                                    0                                                                   4                                 2
10                     0              3                                 2                  2                                           2                                                                    0                                                                   3                                 5
11                     0              4                                 5                  1                                           0                                                                    0                                                                   3                                 3
12                     0              2                                 3                  0                                           2                                                                    0                                                                   2                                 2
13                     0              2                                 3                  2                                           0                                                                    0                                                                   4                                 2
14                     0              3                                 4                  2                                           1                                                                    1                                                                   3                                 4
15                     0              5                                 5                  0                                           0                                                                    0                                                                   4                                 4
16                     0              3                                 3                  1                                           0                                                                    0                                                                   5                                 5
17                     0              3                                 5                  2                                           0                                                                    0                                                                   5                                 4
18                     0              3                                 3                  1                                           2                                                                    0                                                                   4                                 3
19                     0              3                                 4                  1                                           1                                                                    0                                                                   4                                 3
20                     0              4                                 3                  1                                           0                                                                    0                                                                   4                                 4
21                     0              3                                 3                  1                                           0                                                                    0                                                                   4                                 3
22                     0              3                                 3                  1                                           0                                                                    0                                                                   4                                 3
23                     0              5                                 1                  2                                           0                                                                    0                                                                   5                                 3
24                     0              4                                 5                  2                                           0                                                                    0                                                                   4                                 4
25                     0              4                                 3                  1                                           0                                                                    0                                                                   4                                 4
26                     0              4                                 5                  2                                           0                                                                    2                                                                   4                                 5
27                     1              3                                 4                  2                                           0                                                                    0                                                                   3                                 4
28                     0              5                                 1                  2                                           1                                                                    0                                                                   4                                 5
29                     0              4                                 3                  1                                           0                                                                    0                                                                   5                                 4
30                     0              5                                 5                  2                                           2                                                                    2                                                                   5                                 5
31                     0              3                                 1                  2                                           2                                                                    0                                                                   4                                 4
32                     0              3                                 2                  1                                           2                                                                    0                                                                   4                                 3
33                     0              1                                 1                  1                                           0                                                                    1                                                                   1                                 1
34                     0              1                                 1                  1                                           1                                                                    1                                                                   4                                 3
35                     0              3                                 4                  0                                           0                                                                    0                                                                   5                                 4
36                     0              4                                 5                  2                                           2                                                                    2                                                                   2                                 3
37                     0              1                                 4                  1                                           0                                                                    0                                                                   4                                 4
38                     0              3                                 4                  1                                           0                                                                    0                                                                   3                                 4
39                     0              3                                 2                  1                                           1                                                                    0                                                                   3                                 4
40                     0              3                                 4                  2                                           0                                                                    0                                                                   5                                 5
41                     2              3                                 5                  1                                           0                                                                    0                                                                   3                                 3
42                     0              3                                 5                  1                                           0                                                                    0                                                                   4                                 5
43                     0              5                                 4                  2                                           2                                                                    0                                                                   5                                 5
44                     0              4                                 2                  0                                           0                                                                    0                                                                   2                                 2
45                     0              3                                 2                  1                                           0                                                                    0                                                                   4                                 3
46                     0              5                                 5                  0                                           2                                                                    1                                                                   4                                 5
47                     0              2                                 4                  1                                           0                                                                    0                                                                   4                                 4
48                     0              3                                 4                  0                                           2                                                                    2                                                                   4                                 5
49                     0              2                                 3                  2                                           1                                                                    0                                                                   2                                 3
50                     0              3                                 3                  1                                           0                                                                    0                                                                   4                                 3
51                     0              4                                 4                  0                                           0                                                                    0                                                                   5                                 4
52                     0              4                                 5                  1                                           0                                                                    0                                                                   4                                 4
53                     0              3                                 3                  2                                           2                                                                    2                                                                   3                                 3
54                     0              3                                 1                  0                                           0                                                                    2                                                                   4                                 4
55                     0              3                                 2                  1                                           0                                                                    0                                                                   5                                 4
56                     2              4                                 4                  2                                           0                                                                    1                                                                   4                                 4
57                     0              3                                 1                  0                                           0                                                                    0                                                                   4                                 3
58                     0              2                                 3                  2                                           0                                                                    0                                                                   3                                 5
59                     0              3                                 1                  0                                           0                                                                    0                                                                   5                                 4
60                     0              2                                 1                  1                                           2                                                                    0                                                                   3                                 2
61                     0              2                                 3                  1                                           0                                                                    0                                                                   4                                 4
62                     0              4                                 4                  2                                           2                                                                    0                                                                   4                                 4

In [21]:
model = KMeans(n_clusters = 2)
model.fit(X)

KMeans(n_clusters=2)

### **User Input**

In [23]:
X.columns

Index(['Your Academic Stage', 'Peer pressure',
       'Academic pressure from your home', 'Study Environment',
       'What coping strategy you use as a student?',
       'Do you have any bad habits like smoking, drinking on a daily basis?',
       'What would you rate the academic  competition in your student life',
       'Rate your academic stress index '],
      dtype='object')

In [41]:
"""
'Your Academic Stage':{'undergraduate':0, 'high school':1, 'post-graduate':2},
    'Study Environment':{'Noisy':0, 'Peaceful':1, 'disrupted':2},
    'What coping strategy you use as a student?':{'Analyze the situation and handle it with intellect':0,
       'Social support (friends, family)':1,
       'Emotional breakdown (crying a lot)':2},
    'Do you have any bad habits like smoking, drinking on a daily basis?':{'No':0, 'prefer not to say':1, 'Yes':2}
"""


A =int(input("Your Academic Stage -{'graduate':0, 'high school':1, 'post-graduate':2 :- "))
B=int(input("Peer pressure [ 1 To 5] :- "))
C =int(input("Academic pressure from your home [1 To 5] :- "))
D = int(input("Study Environment -{'Noisy':0, 'Peaceful':1, 'disrupted':2} :- "))
E=int(input("What coping strategy you use as a student? -{'Analyze the situation and handle it with intellect':0,'Social support (friends, family)':1'Emotional breakdown (crying a lot)':2} :- "))
F=int(input("Do you have any bad habits like smoking, drinking on a daily basis? - {'No':0, 'prefer not to say':1, 'Yes':2} :- "))
G=int(input("What would you rate the academic  competition in your student life - [1 To 5] :- "))
H=int(input("Rate your academic stress index -[1 To 5] :- "))

user_input=([A,B,C,D,E,F,G,H])

y_pred = model.predict([user_input])

if ( A == 1 and y_pred == [1]):
  print("As you are a High School Student : Don’t take studies as a burden. Focus on learning, not just on marks. Keep a balance between books and hobbies—play games, draw, dance, or listen to music. Don’t compare yourself with others; everyone has their own path. If you feel pressure, talk to your teachers or parents—sharing always reduces stress.")
elif (A == 0  and y_pred == [1] ):
  print("As you are a Graduate  Student : This is the stage where you start worrying about your career, but remember: skills are more important than grades alone. Join clubs, participate in activities, and explore what you enjoy. Manage your time smartly and don’t push yourself into burnout. If things feel heavy, seek guidance from mentors or friends—college is not just about studying, it’s about discovering yourself.")
elif (A == 2 and y_pred == [1]) :
  print("As you are a Post-Graduate Student : Post-graduation brings pressure from research, deadlines, and the future. Remember, you’re not alone—many go through the same stress. Take breaks, stay physically active, and don’t let perfectionism consume you. Network with peers, share your struggles, and celebrate small progress. It’s okay to rest—it’s not wasted time, it’s recharging for better focus.")
else:
  print("Peaceful students become powerful learners And Your one of them!!")

Your Academic Stage -{'graduate':0, 'high school':1, 'post-graduate':2 :- 0
Peer pressure [ 1 To 5] :- 4
Academic pressure from your home [1 To 5] :- 4
Study Environment -{'Noisy':0, 'Peaceful':1, 'disrupted':2} :- 0
What coping strategy you use as a student? -{'Analyze the situation and handle it with intellect':0,'Social support (friends, family)':1'Emotional breakdown (crying a lot)':2} :- 2
Do you have any bad habits like smoking, drinking on a daily basis? - {'No':0, 'prefer not to say':1, 'Yes':2} :- 0
What would you rate the academic  competition in your student life - [1 To 5] :- 3
Rate your academic stress index -[1 To 5] :- 4
As you are a Graduate School Student : This is the stage where you start worrying about your career, but remember: skills are more important than grades alone. Join clubs, participate in activities, and explore what you enjoy. Manage your time smartly and don’t push yourself into burnout. If things feel heavy, seek guidance from mentors or friends—college is not just about studying, it’s about discovering yourself.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(

In [37]:
model.predict([[0,3,3,1,0,0,4,5]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(

array([1], dtype=int32)

In [38]:
model.predict([[ 2, 4,4, 0, 0 ,   0 , 4 , 3]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(

array([1], dtype=int32)

In [31]:
model.predict([[1,4, 4 , 1 , 0 ,  0 ,  3,4]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(

array([1], dtype=int32)

In [32]:
model.predict([[1,1,1,1,0,0,1,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(

array([0], dtype=int32)