In [3]:
import pandas as pd
df = pd.read_csv('/content/optimal_fertilizer_dataset_5000.csv')
df

,Soil_Type,Crop_Type,Soil_pH,Nitrogen,Phosphorus,Potassium,Moisture_Level,Rainfall,Temperature,Recommended_Fertilizer
0,Chalky,Rice,6.0,43,37,45,33.8,137,30.4,10-26-26
1,Sandy,Barley,6.9,53,54,35,13.9,231,20.7,10-26-26
2,Silty,Rice,4.7,43,25,43,31.7,139,28.2,10-26-26
3,Peaty,Sugarcane,7.3,43,55,42,10.5,246,34.5,10-26-26
4,Chalky,Sugarcane,7.8,93,34,58,15.3,230,21.1,NPK
...,...,...,...,...,...,...,...,...,...,...
4995,Clay,Barley,6.3,111,27,75,29.8,220,31.1,10-26-26
4996,Peaty,Cotton,7.2,84,60,52,31.4,215,34.0,DAP
4997,Sandy,Maize,6.8,76,41,55,15.9,183,24.8,DAP
4998,Sandy,Soybean,7.5,61,58,80,26.3,174,21.0,DAP
4999,Clay,Cotton,4.7,118,51,33,27.1,160,22.3,10-26-26

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Soil_Type               5000 non-null   object
 1   Crop_Type               5000 non-null   object
 2   Soil_pH                 5000 non-null   float64
 3   Nitrogen                5000 non-null   int64
 4   Phosphorus              5000 non-null   int64
 5   Potassium               5000 non-null   int64
 6   Moisture_Level          5000 non-null   float64
 7   Rainfall                5000 non-null   int64
 8   Temperature             5000 non-null   float64
 9   Recommended_Fertilizer  5000 non-null   object
dtypes: float64(3), int64(4), object(3)
memory usage: 390.8+ KB

In [5]:
df.isna().sum()

Soil_Type                 0
Crop_Type                 0
Soil_pH                   0
Nitrogen                  0
Phosphorus                0
Potassium                 0
Moisture_Level            0
Rainfall                  0
Temperature               0
Recommended_Fertilizer    0
dtype: int64

In [6]:
df['Moisture_Level'].unique()

array([33.8, 13.9, 31.7, 10.5, 15.3, 17.6, 17.3, 29.6, 24.8, 14.3, 34.1,
       12.4, 13.1, 32.7, 17.8, 14.6, 33.5, 33. , 11.1, 16.8, 17. , 30.1,
       29.3, 30.4, 12.9, 18.3, 18.1, 32.2, 27.8, 20.7, 10.8, 22.7, 20.3,
       11.9, 33.2, 31.8, 32.3, 32.4, 15.7, 31.5, 20.4, 18.4, 23. , 34.3,
       22.4, 10.9, 11.3, 16. , 34.6, 29. , 19.2, 23.4, 18. , 22.8, 14.4,
       33.4, 12.8, 16.4, 23.9, 12.3, 25.8, 28.1, 29.5, 14. , 10.2, 10.1,
       27.3, 28.7, 26.4, 24.4, 26.1, 10.4, 34.2, 17.4, 17.9, 13.5, 28.5,
       19. , 30.3, 26.2, 21.6, 30.6, 23.1, 25.6, 23.3, 28.2, 21. , 20.2,
       16.3, 26.5, 28.4, 20.5, 28.9, 11.2, 27.6, 22.3, 20.8, 25.9, 32.6,
       12.5, 27.1, 31.1, 25.7, 28.8, 18.5, 12.6, 30.7, 19.7, 21.2, 26.8,
       29.7, 11.4, 13.6, 11.8, 12. , 19.4, 33.7, 24. , 21.7, 24.6, 17.1,
       34.8, 27.4, 21.4, 14.7, 34.7, 17.7, 14.1, 24.9, 31.6, 34.9, 33.6,
       21.3, 25.2, 25.5, 13.4, 24.7, 21.5, 18.2, 13.8, 14.5, 21.8, 14.8,
       13. , 19.1, 11. , 11.5, 19.3, 12.7, 16.1, 22.5, 13.2, 29.2, 20.6,
       24.5, 27. , 29.9, 19.8, 32.5, 28.6, 29.1, 30.5, 13.7, 28. , 23.6,
       20. , 25.3, 33.3, 33.1, 31. , 18.7, 26.6, 11.7, 11.6, 10.6, 15.8,
       26.3, 30.8, 15.1, 10.3, 10.7, 30.9, 32.9, 16.9, 19.6, 14.2, 25.1,
       17.2, 15.4, 16.2, 28.3, 22.2, 25.4, 23.2, 15.5, 12.2, 18.8, 32.1,
       15.6, 31.9, 30.2, 16.5, 22. , 16.7, 27.7, 34.5, 27.2, 18.6, 21.1,
       12.1, 26. , 13.3, 22.9, 30. , 23.5, 27.9, 23.7, 34.4, 15. , 32.8,
       15.9, 31.4, 21.9, 24.3, 19.9, 26.7, 19.5, 18.9, 25. , 15.2, 34. ,
       20.9, 24.1, 35. , 33.9, 32. , 29.8, 31.3, 26.9, 23.8, 17.5, 20.1,
       16.6, 10. , 31.2, 27.5, 22.6, 22.1, 24.2, 29.4, 14.9])

In [7]:
df['Crop_Type'].unique()

array(['Rice', 'Barley', 'Sugarcane', 'Soybean', 'Maize', 'Cotton',
       'Wheat'], dtype=object)

In [8]:
df['Soil_Type'].unique()

array(['Chalky', 'Sandy', 'Silty', 'Peaty', 'Loamy', 'Clay'], dtype=object)

In [9]:
df['Recommended_Fertilizer'].unique()

array(['10-26-26', 'NPK', 'DAP', 'Urea', 'Compost', 'Vermicompost'],
      dtype=object)

In [10]:
df.replace({
    'Crop_Type':{'Rice':0, 'Barley':1, 'Sugarcane':2, 'Soybean':3, 'Maize':4, 'Cotton':5,'Wheat':6},
    'Soil_Type' : {'Chalky':0, 'Sandy':1, 'Silty':2, 'Peaty':3, 'Loamy':4, 'Clay':5},
    'Recommended_Fertilizer':{'10-26-26':0, 'NPK':1, 'DAP':2, 'Urea':3, 'Compost':4, 'Vermicompost':5}

},inplace =True)

/tmp/ipython-input-10-642748733.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({

In [11]:
df

,Soil_Type,Crop_Type,Soil_pH,Nitrogen,Phosphorus,Potassium,Moisture_Level,Rainfall,Temperature,Recommended_Fertilizer
0,0,0,6.0,43,37,45,33.8,137,30.4,0
1,1,1,6.9,53,54,35,13.9,231,20.7,0
2,2,0,4.7,43,25,43,31.7,139,28.2,0
3,3,2,7.3,43,55,42,10.5,246,34.5,0
4,0,2,7.8,93,34,58,15.3,230,21.1,1
...,...,...,...,...,...,...,...,...,...,...
4995,5,1,6.3,111,27,75,29.8,220,31.1,0
4996,3,5,7.2,84,60,52,31.4,215,34.0,2
4997,1,4,6.8,76,41,55,15.9,183,24.8,2
4998,1,3,7.5,61,58,80,26.3,174,21.0,2
4999,5,5,4.7,118,51,33,27.1,160,22.3,0

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X =df.drop("Recommended_Fertilizer",axis = 1)
y = df['Recommended_Fertilizer']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)
model = RandomForestClassifier(n_estimators = 100)

In [13]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [14]:
y_pred = model.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

print("confusion_matrix : ",confusion_matrix(y_test,y_pred))
print("accuracy_score : ",accuracy_score(y_test,y_pred))

confusion_matrix :  [[818   5  10   6   4   5]
 [  4 104  11   6   1   3]
 [  9   2 106   4   4   3]
 [  5   6   5 136   3   8]
 [  3   3   8   2 178   1]
 [  7   8   7  10   4   1]]
accuracy_score :  0.8953333333333333

## **User Input**

In [16]:
df.columns

Index(['Soil_Type', 'Crop_Type', 'Soil_pH', 'Nitrogen', 'Phosphorus',
       'Potassium', 'Moisture_Level', 'Rainfall', 'Temperature',
       'Recommended_Fertilizer'],
      dtype='object')

In [28]:
'''
'Soil_Type', 'Crop_Type', 'Soil_pH', 'Nitrogen', 'Phosphorus',
       'Potassium', 'Moisture_Level', 'Rainfall', 'Temperature',
       'Recommended_Fertilizer'
'''



Soil_Type =int(input("Enter the Soil_Type : {'Chalky':0, 'Sandy':1, 'Silty':2, 'Peaty':3, 'Loamy':4, 'Clay':5}  "))
Crop_Type= int(input("Enter the Crop_Type : {'Rice':0, 'Barley':1, 'Sugarcane':2, 'Soybean':3, 'Maize':4, 'Cotton':5,'Wheat':6} "))

Soil_pH = float(input("Enter the Soil_pH : "))
Nitrogen = int(input("Enter the Nitrogen : "))
Phosphorus = int(input("Enter the Phosphorus"))
Potassium = int(input("Enter the Potassium"))
Moisture_Level = int(input("Enter the Moisture_Level : "))
Rainfall = int(input("Enter the Rainfall : "))
Temperature = float(input("Enter the Temperature : "))

user_input = [[Soil_Type,Crop_Type,Soil_pH,Nitrogen,Phosphorus,Potassium,Moisture_Level,Rainfall,Temperature]]

y_pred = model.predict(user_input)
#{'10-26-26':0, 'NPK':1, 'DAP':2, 'Urea':3, 'Compost':4, 'Vermicompost':5}

if(y_pred == [0]) :
  print ("You have to use '10-26-26' as a fertilizer to your crop")
elif(y_pred == [1]):
  print ("You have to use 'NPK' as a fertilizer to your crop")
elif(y_pred == [2]):
  print ("You have to use 'DAP' as a fertilizer to your crop")
elif(y_pred == [3]):
  print ("You have to use 'Urea' as a fertilizer to your crop")
elif(y_pred == [4]):
  print ("You have to use 'Compost' as a fertilizer to your crop")
elif(y_pred == [5]):
  print ("You have to use 'Vermicompost' as a fertilizer to your crop")
else:
  print("Please ,Enter the details correctly!!")

Enter the Soil_Type : {'Chalky':0, 'Sandy':1, 'Silty':2, 'Peaty':3, 'Loamy':4, 'Clay':5}  3
Enter the Crop_Type : {'Rice':0, 'Barley':1, 'Sugarcane':2, 'Soybean':3, 'Maize':4, 'Cotton':5,'Wheat':6} 2
Enter the Soil_pH : 23
Enter the Nitrogen : 34
Enter the Phosphorus34
Enter the Potassium34
Enter the Moisture_Level : 34
Enter the Rainfall : 45
Enter the Temperature : 36.7
You have to use '10-26-26' as a fertilizer to your crop

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(