## **Reading the data**

In [6]:
import pandas as pd

data = pd.read_csv("/content/Students Social Media Addiction.csv")
print(data.to_string())

     Student_ID  Age  Gender Academic_Level          Country  Avg_Daily_Usage_Hours Most_Used_Platform Affects_Academic_Performance  Sleep_Hours_Per_Night  Mental_Health_Score Relationship_Status  Conflicts_Over_Social_Media  Addicted_Score
0             1   19  Female  Undergraduate       Bangladesh                    5.2          Instagram                          Yes                    6.5                    6     In Relationship                            3               8
1             2   22    Male       Graduate            India                    2.1            Twitter                           No                    7.5                    8              Single                            0               3
2             3   20  Female  Undergraduate              USA                    6.0             TikTok                          Yes                    5.0                    5         Complicated                            4               9
3             4   18    Male    High School               UK                    3.0            YouTube                           No                    7.0                    7              Single                            1               4
4             5   21    Male       Graduate           Canada                    4.5           Facebook                          Yes                    6.0                    6     In Relationship                            2               7
5             6   19  Female  Undergraduate        Australia                    7.2          Instagram                          Yes                    4.5                    4         Complicated                            5               9
6             7   23    Male       Graduate          Germany                    1.5           LinkedIn                           No                    8.0                    9              Single                            0               2
7             8   20  Female  Undergraduate           Brazil                    5.8           Snapchat                          Yes                    6.0                    6     In Relationship                            2               8
8             9   18    Male    High School            Japan                    4.0             TikTok                           No                    6.5                    7              Single                            1               5
9            10   21  Female       Graduate      South Korea                    3.3          Instagram                           No                    7.0                    7     In Relationship                            1               4
10           11   19    Male  Undergraduate           France                    4.8           Snapchat                          Yes                    6.2                    5         Complicated                            3               7
11           12   20  Female  Undergraduate            Spain                    5.5             TikTok                          Yes                    5.8                    6     In Relationship                            2               8
12           13   22    Male       Graduate            Italy                    2.8           LinkedIn                           No                    7.2                    8              Single                            1               4
13           14   18  Female    High School           Mexico                    6.5          Instagram                          Yes                    5.5                    5              Single                            4               9
14           15   21    Male  Undergraduate           Russia                    3.7            YouTube                           No                    6.8                    7     In Relationship                            2               5
15           16   20  Female  Undergraduate            China                    4.2             TikTok                          Yes                    6.0                    6         Complicated                            3               7
16           17   24    Male       Graduate           Sweden                    2.0           LinkedIn                           No                    7.8                    8              Single                            0               3
17           18   19  Female    High School           Norway                    5.0          Instagram                          Yes                    5.7                    5     In Relationship                            3               8
18           19   21    Male  Undergraduate          Denmark                    3.5           Facebook                           No                    6.7                    7              Single                            1               5
19           20   20  Female  Undergraduate      Netherlands                    4.7           Snapchat                          Yes                    5.9                    6         Complicated                            3               7
20           21   18    Male    High School          Belgium                    5.3             TikTok                          Yes                    5.5                    5              Single                            4               8
21           22   23  Female       Graduate      Switzerland                    2.5           LinkedIn                           No                    7.3                    8     In Relationship                            1               4
22           23   19    Male  Undergraduate          Austria                    4.9          Instagram                          Yes                    5.8                    6         Complicated                            3               7
23           24   20  Female  Undergraduate         Portugal                    5.7             TikTok                          Yes                    5.4                    5              Single                            4               8
24           25   22    Male       Graduate           Greece                    3.2           Facebook                           No                    6.9                    7     In Relationship                            2               5
25           26   19  Female    High School          Ireland                    6.1          Instagram                          Yes                    5.2                    5         Complicated                            4               9
26           27   21    Male  Undergraduate      New Zealand                    3.8            YouTube                           No                    6.6                    7              Single                            1               5
27           28   20  Female  Undergraduate        Singapore                    4.4             TikTok                          Yes                    5.9                    6     In Relationship                            3               7
28           29   24    Male       Graduate         Malaysia                    2.2           LinkedIn                           No                    7.4                    8              Single                            0               3
29           30   19  Female    High School         Thailand                    5.9          Instagram                          Yes                    5.3                    5         Complicated                            4               8
30           31   21    Male  Undergraduate          Vietnam                    3.6           Facebook                           No                    6.7                    7              Single                            1               5
31           32   20  Female  Undergraduate      Philippines                    4.8           Snapchat                          Yes                    5.7                    6     In Relationship                            3               7
32           33   18    Male    High School        Indonesia                    5.4             TikTok                          Yes                    5.4                    5         Complicated                            4               8
33           34   23  Female       Graduate           Taiwan                    2.6           LinkedIn                           No                    7.2                    8              Single                            1               4
34           35   19    Male  Undergraduate        Hong Kong                    4.7          Instagram                          Yes                    5.8                    6     In Relationship                            3               7
35           36   20  Female  Undergraduate           Turkey                    5.6             TikTok                          Yes                    5.5                    5         Complicated                            4               8
36           37   22    Male       Graduate           Israel                    3.1           Facebook                           No                    6.8                    7              Single                            1               5
37           38   19  Female    High School              UAE                    6.2          Instagram                          Yes                    5.1                    5     In Relationship                            4               9
38           39   21    Male  Undergraduate            Egypt                    3.9            YouTube                           No                    6.5                    7         Complicated                            2               6
39           40   20  Female  Undergraduate          Morocco                    4.5             TikTok                          Yes                    5.8                    6              Single                            3               7
40           41   24    Male       Graduate     South Africa                    2.3           LinkedIn                           No                    7.3                    8     In Relationship                            1               4
41           42   19  Female    High School          Nigeria                    5.8          Instagram                          Yes                    5.4                    5         Complicated                            4               8
42           43   21    Male  Undergraduate            Kenya                    3.7           Facebook                           No                    6.6                    7              Single                            2               5
43           44   20  Female  Undergraduate            Ghana                    4.6           Snapchat                          Yes                    5.7                    6     In Relationship                            3               7
44           45   18    Male    High School        Argentina                    5.5             TikTok                          Yes                    5.3                    5              Single                            4               8
45           46   23  Female       Graduate            Chile                    2.7           LinkedIn                           No                    7.1                    8         Complicated                            1               4
46           47   19    Male  Undergraduate         Colombia                    4.8          Instagram                          Yes                    5.9                    6     In Relationship                            3               7
47           48   20  Female  Undergraduate             Peru                    5.5             TikTok                          Yes                    5.6                    5              Single                            4               8
48           49   22    Male       Graduate        Venezuela                    3.3           Facebook                           No                    6.7                    7     In Relationship                            2               5
49           50   19  Female    High School          Ecuador                    6.3          Instagram                          Yes                    5.2                    5         Complicated                            4               9
50           51   21    Male  Undergraduate          Uruguay                    3.8            YouTube                           No                    6.4                    7              Single                            2               6
51           52   20  Female  Undergraduate         Paraguay                    4.7             TikTok                          Yes                    5.8                    6     In Relationship                            3               7
52           53   24    Male       Graduate          Bolivia                    2.4           LinkedIn                           No                    7.2                    8         Complicated                            1               4
53           54   19  Female    High School       Costa Rica                    5.7          Instagram                          Yes                    5.5                    5              Single                            4               8
54           55   21    Male  Undergraduate           Panama                    3.6           Facebook                           No                    6.5                    7     In Relationship                            2               5
55           56   20  Female  Undergraduate          Jamaica                    4.9           Snapchat                          Yes                    5.6                    6         Complicated                            3               7
56           57   18    Male    High School         Trinidad                    5.6             TikTok                          Yes                    5.2                    5              Single                            4               8
57           58   23  Female       Graduate          Bahamas                    2.8           LinkedIn                           No                    7.0                    8     In Relationship                            1               4
58           59   19    Male  Undergraduate          Iceland                    4.6          Instagram                          Yes                    5.9                    6         Complicated                            3               7
59           60   20  Female  Undergraduate          Finland                    5.4             TikTok                          Yes                    5.7                    5              Single                            4               8
60           61   22    Male       Graduate           Poland                    3.1           Facebook                           No                    7.1                    7              Single                            1               5
61           62   19  Female  Undergraduate          Romania                    5.6          Instagram                          Yes                    5.6                    5     In Relationship                            3               8
62           63   20    Male  Undergraduate          Hungary                    4.2             TikTok                          Yes                    6.0                    6         Complicated                            3               7
63           64   18  Female    High School   Czech Republic                    6.1           Snapchat                          Yes                    5.2                    4              Single                            4               9
64           65   23    Male       Graduate         Slovakia                    2.3           LinkedIn                           No                    7.4                    8     In Relationship                            1               3
65           66   21  Female  Undergraduate          Croatia                    4.8          Instagram                          Yes                    5.8                    6              Single                            3               7
66           67   20    Male  Undergraduate           Serbia                    3.9            YouTube                           No                    6.5                    7         Complicated                            2               6
67           68   19  Female    High School         Slovenia                    5.7             TikTok                          Yes                    5.4                    5     In Relationship                            4               8
68           69   22    Male       Graduate         Bulgaria                    2.8           LinkedIn                           No                    7.2                    8              Single                            1               4
69           70   20  Female  Undergraduate          Estonia                    4.5          Instagram                          Yes                    5.9                    6         Complicated                            3               7
70           71   18    Male    High School           Latvia                    5.4           Snapchat                          Yes                    5.5                    5              Single                            4               8
71           72   21  Female       Graduate        Lithuania                    3.2           Facebook                           No                    6.8                    7     In Relationship                            2               5
72           73   19    Male  Undergraduate          Ukraine                    4.9             TikTok                          Yes                    5.7                    6         Complicated                            3               7
73           74   20  Female  Undergraduate          Moldova                    5.8          Instagram                          Yes                    5.3                    5              Single                            4               8
74           75   23    Male       Graduate          Belarus                    2.5           LinkedIn                           No                    7.3                    8     In Relationship                            1               4
75           76   21  Female  Undergraduate       Kazakhstan                    4.6           Snapchat                          Yes                    5.8                    6              Single                            3               7
76           77   19    Male    High School       Uzbekistan                    5.5             TikTok                          Yes                    5.4                    5         Complicated                            4               8
77           78   22  Female       Graduate       Kyrgyzstan                    2.9           Facebook                           No                    7.0                    7     In Relationship                            2               5
78           79   20    Male  Undergraduate       Tajikistan                    4.7            YouTube                          Yes                    5.9                    6              Single                            3               7
79           80   18  Female    High School          Armenia                    5.9          Instagram                          Yes                    5.2                    5         Complicated                            4               9
80           81   21    Male       Graduate          Georgia                    3.0           LinkedIn                           No                    7.1                    8     In Relationship                            1               4

## **Data Exploration**

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 705 entries, 0 to 704
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    705 non-null    int64
 1   Age                           705 non-null    int64
 2   Gender                        705 non-null    object
 3   Academic_Level                705 non-null    object
 4   Country                       705 non-null    object
 5   Avg_Daily_Usage_Hours         705 non-null    float64
 6   Most_Used_Platform            705 non-null    object
 7   Affects_Academic_Performance  705 non-null    object
 8   Sleep_Hours_Per_Night         705 non-null    float64
 9   Mental_Health_Score           705 non-null    int64
 10  Relationship_Status           705 non-null    object
 11  Conflicts_Over_Social_Media   705 non-null    int64
 12  Addicted_Score                705 non-null    int64
dtypes: float64(2), int64(5), object(6)
memory usage: 71.7+ KB

In [8]:
data['Gender'].value_counts()

Gender
Female    353
Male      352
Name: count, dtype: int64

In [9]:
data['Sleep_Hours_Per_Night'].unique()

array([6.5, 7.5, 5. , 7. , 6. , 4.5, 8. , 6.2, 5.8, 7.2, 5.5, 6.8, 7.8,
       5.7, 6.7, 5.9, 7.3, 5.4, 6.9, 5.2, 6.6, 7.4, 5.3, 5.1, 7.1, 5.6,
       6.4, 6.3, 6.1, 7.6, 7.7, 7.9, 8.1, 8.2, 8.3, 4.9, 8.4, 4.8, 8.5,
       4.7, 8.6, 4.6, 4.4, 8.7, 4.3, 8.8, 4.2, 8.9, 4.1, 9. , 9.1, 9.2,
       9.3, 9.4, 4. , 9.5, 3.9, 9.6, 3.8])

In [10]:
data['Most_Used_Platform'].unique()

array(['Instagram', 'Twitter', 'TikTok', 'YouTube', 'Facebook',
       'LinkedIn', 'Snapchat', 'LINE', 'KakaoTalk', 'VKontakte',
       'WhatsApp', 'WeChat'], dtype=object)

In [11]:
data['Mental_Health_Score'].unique()

array([6, 8, 5, 7, 4, 9])

In [12]:
data['Relationship_Status'].unique()

array(['In Relationship', 'Single', 'Complicated'], dtype=object)

In [13]:
data['Conflicts_Over_Social_Media'].unique()

array([3, 0, 4, 1, 2, 5])

In [14]:
data['Country'].unique()

array(['Bangladesh', 'India', 'USA', 'UK', 'Canada', 'Australia',
       'Germany', 'Brazil', 'Japan', 'South Korea', 'France', 'Spain',
       'Italy', 'Mexico', 'Russia', 'China', 'Sweden', 'Norway',
       'Denmark', 'Netherlands', 'Belgium', 'Switzerland', 'Austria',
       'Portugal', 'Greece', 'Ireland', 'New Zealand', 'Singapore',
       'Malaysia', 'Thailand', 'Vietnam', 'Philippines', 'Indonesia',
       'Taiwan', 'Hong Kong', 'Turkey', 'Israel', 'UAE', 'Egypt',
       'Morocco', 'South Africa', 'Nigeria', 'Kenya', 'Ghana',
       'Argentina', 'Chile', 'Colombia', 'Peru', 'Venezuela', 'Ecuador',
       'Uruguay', 'Paraguay', 'Bolivia', 'Costa Rica', 'Panama',
       'Jamaica', 'Trinidad', 'Bahamas', 'Iceland', 'Finland', 'Poland',
       'Romania', 'Hungary', 'Czech Republic', 'Slovakia', 'Croatia',
       'Serbia', 'Slovenia', 'Bulgaria', 'Estonia', 'Latvia', 'Lithuania',
       'Ukraine', 'Moldova', 'Belarus', 'Kazakhstan', 'Uzbekistan',
       'Kyrgyzstan', 'Tajikistan', 'Armenia', 'Georgia', 'Azerbaijan',
       'Cyprus', 'Malta', 'Luxembourg', 'Monaco', 'Andorra', 'San Marino',
       'Vatican City', 'Liechtenstein', 'Montenegro', 'Albania',
       'North Macedonia', 'Kosovo', 'Bosnia', 'Qatar', 'Kuwait',
       'Bahrain', 'Oman', 'Jordan', 'Lebanon', 'Iraq', 'Yemen', 'Syria',
       'Afghanistan', 'Pakistan', 'Nepal', 'Bhutan', 'Sri Lanka',
       'Maldives'], dtype=object)

In [15]:
data['Country'].value_counts()

Country
India          53
USA            40
Canada         34
France         27
Mexico         27
               ..
Oman            1
Afghanistan     1
Syria           1
Yemen           1
Bhutan          1
Name: count, Length: 110, dtype: int64

In [16]:
data['Academic_Level'].value_counts()

Academic_Level
Undergraduate    353
Graduate         325
High School       27
Name: count, dtype: int64

In [17]:
data['Academic_Level'].unique()

array(['Undergraduate', 'Graduate', 'High School'], dtype=object)

In [18]:
data['Affects_Academic_Performance'].value_counts()

Affects_Academic_Performance
Yes    453
No     252
Name: count, dtype: int64

In [19]:
data['Affects_Academic_Performance'].unique()

array(['Yes', 'No'], dtype=object)

In [20]:
data['Avg_Daily_Usage_Hours'].unique()

array([5.2, 2.1, 6. , 3. , 4.5, 7.2, 1.5, 5.8, 4. , 3.3, 4.8, 5.5, 2.8,
       6.5, 3.7, 4.2, 2. , 5. , 3.5, 4.7, 5.3, 2.5, 4.9, 5.7, 3.2, 6.1,
       3.8, 4.4, 2.2, 5.9, 3.6, 5.4, 2.6, 5.6, 3.1, 6.2, 3.9, 2.3, 4.6,
       2.7, 6.3, 2.4, 2.9, 5.1, 4.3, 4.1, 3.4, 6.4, 7. , 6.8, 6.9, 6.7,
       6.6, 7.1, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3,
       8.4, 8.5])

In [21]:
data['Age'].value_counts()

Age
20    165
19    163
21    156
22    147
23     34
24     26
18     14
Name: count, dtype: int64

## **Encoding the columns : inorder to feed the model**

In [22]:
data.select_dtypes(include= "object")

,Gender,Academic_Level,Country,Most_Used_Platform,Affects_Academic_Performance,Relationship_Status
0,Female,Undergraduate,Bangladesh,Instagram,Yes,In Relationship
1,Male,Graduate,India,Twitter,No,Single
2,Female,Undergraduate,USA,TikTok,Yes,Complicated
3,Male,High School,UK,YouTube,No,Single
4,Male,Graduate,Canada,Facebook,Yes,In Relationship
...,...,...,...,...,...,...
700,Female,Undergraduate,Italy,TikTok,No,In Relationship
701,Male,Graduate,Russia,Instagram,Yes,Single
702,Female,Undergraduate,China,WeChat,Yes,In Relationship
703,Male,Graduate,Japan,Twitter,No,Single
704,Female,Undergraduate,Poland,Facebook,Yes,Single

In [23]:
#array(['Instagram', 'Twitter', 'TikTok', 'YouTube', 'Facebook',
#      'LinkedIn', 'Snapchat', 'LINE', 'KakaoTalk', 'VKontakte',
#       'WhatsApp', 'WeChat'], dtype=object)

data.replace({
    "Gender" :{ "Male" : 0, "Female" : 1},
    "Academic_Level" : { "High School" :0 , "Undergraduate" : 1 , "Graduate" :2},
    "Affects_Academic_Performance" : { "Yes" : 1 ,"No" : 0},
    "Relationship_Status" : { "Single" : 0 , "In Relationship" : 1, "Complicated" : 2}

},inplace = True)

/tmp/ipython-input-23-3541678895.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({

In [24]:
data

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,1,1,Bangladesh,5.2,Instagram,1,6.5,6,1,3,8
1,2,22,0,2,India,2.1,Twitter,0,7.5,8,0,0,3
2,3,20,1,1,USA,6.0,TikTok,1,5.0,5,2,4,9
3,4,18,0,0,UK,3.0,YouTube,0,7.0,7,0,1,4
4,5,21,0,2,Canada,4.5,Facebook,1,6.0,6,1,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,20,1,1,Italy,4.7,TikTok,0,7.2,7,1,2,5
701,702,23,0,2,Russia,6.8,Instagram,1,5.9,4,0,5,9
702,703,21,1,1,China,5.6,WeChat,1,6.7,6,1,3,7
703,704,24,0,2,Japan,4.3,Twitter,0,7.5,8,0,2,4
704,705,19,1,1,Poland,6.2,Facebook,1,6.3,5,0,4,8

In [25]:
data['Addicted_Score'].unique()

array([8, 3, 9, 4, 7, 2, 5, 6])

In [26]:
'''
for i in data['Addicted_Score'] :
  if i > 6:
    data['Addiction'] = 1
  else :
    data['Addiction'] = 0
'''
data['Addiction'] = data['Addicted_Score'].apply(lambda x: 1 if x > 6 else 0)

## **Training the model : Logistic Regression**

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 705 entries, 0 to 704
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    705 non-null    int64
 1   Age                           705 non-null    int64
 2   Gender                        705 non-null    int64
 3   Academic_Level                705 non-null    int64
 4   Country                       705 non-null    object
 5   Avg_Daily_Usage_Hours         705 non-null    float64
 6   Most_Used_Platform            705 non-null    object
 7   Affects_Academic_Performance  705 non-null    int64
 8   Sleep_Hours_Per_Night         705 non-null    float64
 9   Mental_Health_Score           705 non-null    int64
 10  Relationship_Status           705 non-null    int64
 11  Conflicts_Over_Social_Media   705 non-null    int64
 12  Addicted_Score                705 non-null    int64
 13  Addiction                     705 non-null    int64
dtypes: float64(2), int64(10), object(2)
memory usage: 77.2+ KB

In [29]:
X = data[['Student_ID','Age','Academic_Level','Avg_Daily_Usage_Hours','Affects_Academic_Performance','Sleep_Hours_Per_Night','Mental_Health_Score','Conflicts_Over_Social_Media']]
y = data['Addiction']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state =42)

X_train

,Student_ID,Age,Academic_Level,Avg_Daily_Usage_Hours,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Conflicts_Over_Social_Media
24,25,22,2,3.2,0,6.9,7,2
155,156,20,1,4.2,1,7.4,5,4
210,211,20,1,6.3,1,4.4,6,4
260,261,19,1,6.6,1,5.6,4,4
424,425,19,1,2.9,0,8.9,8,2
...,...,...,...,...,...,...,...,...
71,72,21,2,3.2,0,6.8,7,2
106,107,21,1,3.8,0,6.6,7,2
270,271,20,1,4.5,0,7.3,7,2
435,436,22,2,4.4,1,7.8,6,3
102,103,20,1,4.7,1,5.8,6,3

In [30]:
model = LogisticRegression()

model.fit(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [31]:
model.score(X_train,y_train)

0.9804964539007093

In [32]:
y_pred = model.predict(X_test)

## **Model Evaluation : using metrics Accuracy ,precision and recall,f1_score**

In [33]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

Accuracy = accuracy_score(y_test,y_pred)
Recall = recall_score(y_test,y_pred)
Precision = precision_score(y_test,y_pred)
f1_scores = f1_score(y_test,y_pred)

print("Accuracy : ",Accuracy)
print("Recall : ",Recall)
print("Precision : ",Precision)
print("f1_scores : ",f1_scores)

Accuracy :  0.9716312056737588
Recall :  1.0
Precision :  0.9518072289156626
f1_scores :  0.9753086419753086